export const READ_ALL_CHANNELS = "READ_ALL_CHANNELS";
export const READ_ALL_CHANNELS_SUCCESS="READ_ALL_CHANNELS_SUCCESS";
export const READ_ALL_CHANNELS_FAILED="READ_ALL_CHANNELS_FAILED";   

export const SELECTED_CHANNELS = "SELECTED_CHANNELS";

export const GET_UNSELECTED_CHANNELS = "GET_UNSELECTED_CHANNELS"

export const REMOVED_CHANNELS = "REMOVED_CHANNELS";

export const UNSELECTED_CHANNELS = "UNSELECTED_CHANNELS";

export const ADD_TO_SELECTED_CHANNELS = "ADD_TO_SELECTED_CHANNELS";

export const DISABLED_CHANNEL ="DISABLED_CHANNEL";
